"""Add status column to members table

Revision ID: add_status_to_members
Revises: 0556f1fc1beb
Create Date: 2025-12-10 15:37:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_status_to_members'
down_revision = '0556f1fc1beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'status')
    # ### end Alembic commands ###
